M48
; DRILL file {KiCad 7.0.6} date Fri 15 Sep 2023 11:55:38 AM CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-15T11:55:38+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X102.86Y-94.0
X102.86Y-150.0
X142.0Y-94.0
X142.5Y-150.0
T0
M30
