M48
; DRILL file {KiCad 7.0.7} date Mon Oct 16 17:51:24 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-16T17:51:24+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X82.833Y-51.911
X83.146Y-86.602
X111.109Y-86.526
X111.245Y-51.823
T0
M30
