M48
; DRILL file {KiCad 7.0.6} date Sat 30 Sep 2023 04:03:35 PM CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-30T16:03:35+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X82.867Y-45.422
X83.167Y-91.822
X112.467Y-45.322
X112.467Y-91.722
T0
M30
