M48
; DRILL file {KiCad 7.0.7} date Fri Jun  7 19:14:16 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-06-07T19:14:16+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X92.227Y-137.895
X92.65Y-65.4
X168.35Y-65.54
X168.5Y-137.9
T0
M30
